In [45]:
import json
import pandas as pd
#from shapely.geometry import mapping


with open("Raw File/alleghenycounty_streetcenterlines202202.geojson") as f:
    streets = json.load(f)
    
print(streets.keys())
print(streets['type'][0])
print(streets['features'][0])
print(streets['features'][0].keys())

s = streets['features']

dict_keys(['type', 'features'])
F
{'geometry': {'type': 'LineString', 'coordinates': [[-79.74825488808034, 40.610052951852346], [-79.7479751373512, 40.61032360087145], [-79.74750967181487, 40.61075445131801], [-79.74713049703415, 40.61105819930272], [-79.7470952621507, 40.61108489076773]]}, 'type': 'Feature', 'id': 0, 'properties': {'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'GlobalID': '{2143D454-0244-4772-85B7-D06E42AB46C5}', 'CAD_LLO': 847, 'RMUNI': 'BRACKENRIDGE', 'R_ZIP': '15014', 'SOURCE': 'EAMS', 'FCC': 'A31', 'LLO': 847, 'CAD_RLO': 804, 'SOURCE_ID': 0, 'CAD_RHI': 898, 'LMUNI': 'BRACKENRIDGE', 'OBJECTID': 69185, 'L_ZIP': '15014', 'LHI': 847, 'RSTATE': 'PA', 'EDIT_USER': 't096517', 'FULL_NAME': '10TH AVE', 'FEATURE_KE': 69185, 'Shape_Leng': 495.36588114, 'R_STREET_I': 1, 'L_STREET_I': 1, 'ST_NAME': '10TH', 'LCOUNTY': 'ALLEGHENY', 'RLO': 804, 'LSTATE': 'PA', 'ST_TYPE': 'AVE', 'RHI': 804, 'RCOUNTY': 'ALLEGHENY', 'SPEED': 35}}
dict_keys(['geometry', 'type', 'id', 'properties'])

In [46]:
print(len(s))

df = pd.DataFrame.from_dict(s)
df.reset_index(inplace=True)
df = df.rename(columns = {'index':'index'})
display(df)

81234

,index,geometry,type,id,properties
0,0,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,0,"{'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'G..."
1,1,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,1,"{'CAD_LHI': 825, 'EDIT_DATE': '2020-11-25', 'G..."
2,2,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,2,"{'CAD_LHI': 807, 'EDIT_DATE': '2020-11-25', 'G..."
3,3,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,3,"{'CAD_LHI': 799, 'EDIT_DATE': '2016-08-29', 'G..."
4,4,"{'type': 'LineString', 'coordinates': [[-79.75...",Feature,4,"{'CAD_LHI': 713, 'EDIT_DATE': '2016-08-29', 'G..."
...,...,...,...,...,...
81229,81229,"{'type': 'LineString', 'coordinates': [[-79.87...",Feature,81229,"{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo..."
81230,81230,"{'type': 'LineString', 'coordinates': [[-79.87...",Feature,81230,"{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo..."
81231,81231,"{'type': 'LineString', 'coordinates': [[-80.18...",Feature,81231,"{'CAD_LHI': 227, 'EDIT_DATE': '2022-01-31', 'G..."
81232,81232,"{'type': 'LineString', 'coordinates': [[-80.14...",Feature,81232,"{'CAD_LHI': 2709, 'EDIT_DATE': '2022-02-01', '..."
81233,81233,"{'type': 'LineString', 'coordinates': [[-79.96...",Feature,81233,"{'CAD_LHI': 5155, 'EDIT_DATE': '2022-02-01', '..."

In [47]:
#display(df['properties'])
prop = df['properties']

p = pd.DataFrame.from_dict(prop.tolist())
p.reset_index(inplace=True)
p = p.rename(columns = {'index':'index'})
#display(p)

#df.merge(p, how="right", on="index")
#display(df)

df = pd.concat([df,p], axis=1, join='inner')
#df.drop("properties")
#display(df)
#df = df.drop('ST_NAME')
display(df)

,index,geometry,type,id,properties,index,CAD_LHI,EDIT_DATE,GlobalID,CAD_LLO,...,RHI,RCOUNTY,SPEED,ST_PREFIX,ONEWAY,A1,A2,ST_SUFFIX,LARDIR,ST_POSTMOD
0,0,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,0,"{'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'G...",0,899,2016-08-29,{2143D454-0244-4772-85B7-D06E42AB46C5},847,...,804,ALLEGHENY,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,1,"{'CAD_LHI': 825, 'EDIT_DATE': '2020-11-25', 'G...",1,825,2020-11-25,{92DC111C-7D42-42F5-83C4-538FE13E15A6},809,...,802,ALLEGHENY,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,2,"{'CAD_LHI': 807, 'EDIT_DATE': '2020-11-25', 'G...",2,807,2020-11-25,{DF65E1EC-F9D4-43B7-B451-96A5C896964C},801,...,800,ALLEGHENY,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"{'type': 'LineString', 'coordinates': [[-79.74...",Feature,3,"{'CAD_LHI': 799, 'EDIT_DATE': '2016-08-29', 'G...",3,799,2016-08-29,{97363910-0DC0-4C93-B5DA-5C1F4F73BF6D},731,...,738,ALLEGHENY,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"{'type': 'LineString', 'coordinates': [[-79.75...",Feature,4,"{'CAD_LHI': 713, 'EDIT_DATE': '2016-08-29', 'G...",4,713,2016-08-29,{9EE4B927-383B-4976-AA7A-B293BCEB9D00},701,...,712,ALLEGHENY,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81229,81229,"{'type': 'LineString', 'coordinates': [[-79.87...",Feature,81229,"{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",81229,0,2022-01-31,{A5066C23-AEAE-4B4B-877D-6B8566A41BEF},0,...,309,ALLEGHENY,25,NaN,FT,NaN,NaN,NaN,NaN,NaN
81230,81230,"{'type': 'LineString', 'coordinates': [[-79.87...",Feature,81230,"{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",81230,0,2022-01-31,{F716953D-CB16-4399-A469-CAAFF6F2F918},0,...,0,ALLEGHENY,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81231,81231,"{'type': 'LineString', 'coordinates': [[-80.18...",Feature,81231,"{'CAD_LHI': 227, 'EDIT_DATE': '2022-01-31', 'G...",81231,227,2022-01-31,{27F7B154-5DB2-400F-9F17-F579BF0920E6},101,...,118,ALLEGHENY,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81232,81232,"{'type': 'LineString', 'coordinates': [[-80.14...",Feature,81232,"{'CAD_LHI': 2709, 'EDIT_DATE': '2022-02-01', '...",81232,2709,2022-02-01,{71357162-F558-45D0-9E03-510DB61FBE97},2641,...,2706,ALLEGHENY,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81233,81233,"{'type': 'LineString', 'coordinates': [[-79.96...",Feature,81233,"{'CAD_LHI': 5155, 'EDIT_DATE': '2022-02-01', '...",81233,5155,2022-02-01,{E34ACBA4-C9A5-4924-8C57-81D15DC88CEC},5117,...,5156,ALLEGHENY,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
#display(df['properties'])
geo = df['geometry']

g = pd.DataFrame.from_dict(geo.tolist())
g.reset_index(inplace=True)
g = g.rename(columns = {'index':'index'})
#display(g)

#df.merge(g, how="right", on="index")
#display(df)

df = pd.concat([df,g], axis=1, join='inner')
#df.drop("properties")
#display(df)
#display(df.columns)

dfsimplified = df[["id", 'index', 'geometry', 'properties', 'ST_NAME','ST_TYPE','ST_NAME', 'LCOUNTY','SPEED', 'ST_PREFIX','ST_SUFFIX','coordinates' ]]
display(dfsimplified)

,id,index,index,index,geometry,properties,ST_NAME,ST_TYPE,ST_NAME,LCOUNTY,SPEED,ST_PREFIX,ST_SUFFIX,coordinates
0,0,0,0,0,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,10TH,ALLEGHENY,35,NaN,NaN,"[[-79.74825488808034, 40.610052951852346], [-7..."
1,1,1,1,1,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 825, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,10TH,ALLEGHENY,35,NaN,NaN,"[[-79.74870778498493, 40.60960946255759], [-79..."
2,2,2,2,2,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 807, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,10TH,ALLEGHENY,35,NaN,NaN,"[[-79.74893509150469, 40.6093783413925], [-79...."
3,3,3,3,3,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 799, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,10TH,ALLEGHENY,35,NaN,NaN,"[[-79.74946562753058, 40.60904657813747], [-79..."
4,4,4,4,4,"{'type': 'LineString', 'coordinates': [[-79.75...","{'CAD_LHI': 713, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,10TH,ALLEGHENY,35,NaN,NaN,"[[-79.750464580604, 40.60843936921655], [-79.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81229,81229,81229,81229,81229,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,THOMAS,ALLEGHENY,25,NaN,NaN,"[[-79.87510127705264, 40.41203728416115], [-79..."
81230,81230,81230,81230,81230,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,THOMAS,ALLEGHENY,25,NaN,NaN,"[[-79.87447436971013, 40.41235869202218], [-79..."
81231,81231,81231,81231,81231,"{'type': 'LineString', 'coordinates': [[-80.18...","{'CAD_LHI': 227, 'EDIT_DATE': '2022-01-31', 'G...",MARKETPLACE,AVE,MARKETPLACE,ALLEGHENY,25,NaN,NaN,"[[-80.1871724705416, 40.47217177456653], [-80...."
81232,81232,81232,81232,81232,"{'type': 'LineString', 'coordinates': [[-80.14...","{'CAD_LHI': 2709, 'EDIT_DATE': '2022-02-01', '...",SALERNO,DR,SALERNO,ALLEGHENY,25,NaN,NaN,"[[-80.14615584112333, 40.38399889326013], [-80..."
81233,81233,81233,81233,81233,"{'type': 'LineString', 'coordinates': [[-79.96...","{'CAD_LHI': 5155, 'EDIT_DATE': '2022-02-01', '...",RIDGE,DR,RIDGE,ALLEGHENY,25,NaN,NaN,"[[-79.9654781231118, 40.35687536436287], [-79...."

In [50]:
coordinates = dfsimplified['coordinates']



for i in range(10):
    display(coordinates[i])

[[-79.74825488808034, 40.610052951852346],
 [-79.7479751373512, 40.61032360087145],
 [-79.74750967181487, 40.61075445131801],
 [-79.74713049703415, 40.61105819930272],
 [-79.7470952621507, 40.61108489076773]]

[[-79.74870778498493, 40.60960946255759],
 [-79.74865618125855, 40.60966114554043],
 [-79.74825488808034, 40.610052951852346]]

[[-79.74893509150469, 40.6093783413925],
 [-79.74870778498493, 40.60960946255759]]

[[-79.74946562753058, 40.60904657813747],
 [-79.74893509150469, 40.6093783413925]]

[[-79.750464580604, 40.60843936921655],
 [-79.75012032840067, 40.60865020453219],
 [-79.75009201192937, 40.60866716700893],
 [-79.74995124798461, 40.608749219552145]]

[[-79.74995124798461, 40.608749219552145],
 [-79.74977062660462, 40.60885392563107],
 [-79.7497220338143, 40.60888565241994],
 [-79.7496131660235, 40.60894999306261],
 [-79.74946562753058, 40.60904657813747]]

[[-79.72998504054131, 40.61325585610688],
 [-79.72878458896744, 40.613537882255436],
 [-79.72868530643015, 40.61356154249354]]

[[-79.73153789450139, 40.612890228980454],
 [-79.73073462379286, 40.6130789952676],
 [-79.73069973631371, 40.6130871420443],
 [-79.72998504054131, 40.61325585610688]]

[[-79.73331703720018, 40.61247128585265],
 [-79.73310415547435, 40.6125216056637],
 [-79.73269271278906, 40.61261925074055],
 [-79.73243780178223, 40.612679898087116],
 [-79.7316711822577, 40.61285912068465],
 [-79.73153789450139, 40.612890228980454]]

[[-79.73418370551904, 40.6122642548564],
 [-79.73398606723778, 40.61231225606875],
 [-79.73331703720018, 40.61247128585265]]

In [64]:
dfsimplified['color'] = 0

display(dfsimplified)

,id,index,geometry,properties,ST_NAME,ST_TYPE,LCOUNTY,SPEED,ST_PREFIX,ST_SUFFIX,coordinates,color
0,0,0,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74825488808034, 40.610052951852346], [-7...",0
1,1,1,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 825, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74870778498493, 40.60960946255759], [-79...",0
2,2,2,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 807, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74893509150469, 40.6093783413925], [-79....",0
3,3,3,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 799, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74946562753058, 40.60904657813747], [-79...",0
4,4,4,"{'type': 'LineString', 'coordinates': [[-79.75...","{'CAD_LHI': 713, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.750464580604, 40.60843936921655], [-79.7...",0
...,...,...,...,...,...,...,...,...,...,...,...,...
81229,81229,81229,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,ALLEGHENY,25,NaN,NaN,"[[-79.87510127705264, 40.41203728416115], [-79...",0
81230,81230,81230,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,ALLEGHENY,25,NaN,NaN,"[[-79.87447436971013, 40.41235869202218], [-79...",0
81231,81231,81231,"{'type': 'LineString', 'coordinates': [[-80.18...","{'CAD_LHI': 227, 'EDIT_DATE': '2022-01-31', 'G...",MARKETPLACE,AVE,ALLEGHENY,25,NaN,NaN,"[[-80.1871724705416, 40.47217177456653], [-80....",0
81232,81232,81232,"{'type': 'LineString', 'coordinates': [[-80.14...","{'CAD_LHI': 2709, 'EDIT_DATE': '2022-02-01', '...",SALERNO,DR,ALLEGHENY,25,NaN,NaN,"[[-80.14615584112333, 40.38399889326013], [-80...",0
81233,81233,81233,"{'type': 'LineString', 'coordinates': [[-79.96...","{'CAD_LHI': 5155, 'EDIT_DATE': '2022-02-01', '...",RIDGE,DR,ALLEGHENY,25,NaN,NaN,"[[-79.9654781231118, 40.35687536436287], [-79....",0

In [65]:
point = (-79.7789, 40.44444)

i = 0
row = 0
distance = (100,100)
flag = False

for coordinateList in coordinates:
    for p in coordinateList:
        currentDis = (abs(point[0] - p[0]), abs(point[1] - p[1]))
        #print(currentDis)
        if((currentDis[0] + currentDis[1]) <= (distance[0] + distance[1])):
            distance = currentDis
            flag = True
        #print(distance)
        #print("----------------------------------------")
    if(flag):
        flag = False
        row = i
    i+=1

#print(row)
dfsimplified['color'][row] = 1
#for x in range(100):
#    dfsimplified['color'][x] = 1
display(dfsimplified['color'][row])
#display(dfsimplified)
#dfsimplified=dfsimplified.drop(columns='index')
dfsimplified = dfsimplified.loc[:,~dfsimplified.columns.duplicated()]
display(dfsimplified)

<ipython-input-65-78ea408ba82a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfsimplified['color'][row] = 1

1

,id,index,geometry,properties,ST_NAME,ST_TYPE,LCOUNTY,SPEED,ST_PREFIX,ST_SUFFIX,coordinates,color
0,0,0,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74825488808034, 40.610052951852346], [-7...",0
1,1,1,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 825, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74870778498493, 40.60960946255759], [-79...",0
2,2,2,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 807, 'EDIT_DATE': '2020-11-25', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74893509150469, 40.6093783413925], [-79....",0
3,3,3,"{'type': 'LineString', 'coordinates': [[-79.74...","{'CAD_LHI': 799, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.74946562753058, 40.60904657813747], [-79...",0
4,4,4,"{'type': 'LineString', 'coordinates': [[-79.75...","{'CAD_LHI': 713, 'EDIT_DATE': '2016-08-29', 'G...",10TH,AVE,ALLEGHENY,35,NaN,NaN,"[[-79.750464580604, 40.60843936921655], [-79.7...",0
...,...,...,...,...,...,...,...,...,...,...,...,...
81229,81229,81229,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,ALLEGHENY,25,NaN,NaN,"[[-79.87510127705264, 40.41203728416115], [-79...",0
81230,81230,81230,"{'type': 'LineString', 'coordinates': [[-79.87...","{'CAD_LHI': 0, 'EDIT_DATE': '2022-01-31', 'Glo...",THOMAS,WAY,ALLEGHENY,25,NaN,NaN,"[[-79.87447436971013, 40.41235869202218], [-79...",0
81231,81231,81231,"{'type': 'LineString', 'coordinates': [[-80.18...","{'CAD_LHI': 227, 'EDIT_DATE': '2022-01-31', 'G...",MARKETPLACE,AVE,ALLEGHENY,25,NaN,NaN,"[[-80.1871724705416, 40.47217177456653], [-80....",0
81232,81232,81232,"{'type': 'LineString', 'coordinates': [[-80.14...","{'CAD_LHI': 2709, 'EDIT_DATE': '2022-02-01', '...",SALERNO,DR,ALLEGHENY,25,NaN,NaN,"[[-80.14615584112333, 40.38399889326013], [-80...",0
81233,81233,81233,"{'type': 'LineString', 'coordinates': [[-79.96...","{'CAD_LHI': 5155, 'EDIT_DATE': '2022-02-01', '...",RIDGE,DR,ALLEGHENY,25,NaN,NaN,"[[-79.9654781231118, 40.35687536436287], [-79....",0

In [66]:
#with open("Raw File/alleghenycounty_streetcenterlines202202.geojson") as f:
#    newjson = json.load(f)

#A Python dictionary containing properties to be added to each GeoJSON Feature
#Convert the dictionary to a list
properties_list=list(zip(dfsimplified['id'].tolist(), dfsimplified['color'].tolist()))
print("1")
count = 0
#Loop over GeoJSON features and add the new properties
for feat in streets['features']:
    #if(count%2000 == 0):
    #        print(count)
    feat['properties']["color"] = properties_list[count][1]
    count+=1

print("2")
print(streets['features'][0])
#Write result to a new file
with open('new.geojson', 'w') as f:
    json.dump(streets, f)

1
2
{'geometry': {'type': 'LineString', 'coordinates': [[-79.74825488808034, 40.610052951852346], [-79.7479751373512, 40.61032360087145], [-79.74750967181487, 40.61075445131801], [-79.74713049703415, 40.61105819930272], [-79.7470952621507, 40.61108489076773]]}, 'type': 'Feature', 'id': 0, 'properties': {'CAD_LHI': 899, 'EDIT_DATE': '2016-08-29', 'GlobalID': '{2143D454-0244-4772-85B7-D06E42AB46C5}', 'CAD_LLO': 847, 'RMUNI': 'BRACKENRIDGE', 'R_ZIP': '15014', 'SOURCE': 'EAMS', 'FCC': 'A31', 'LLO': 847, 'CAD_RLO': 804, 'SOURCE_ID': 0, 'CAD_RHI': 898, 'LMUNI': 'BRACKENRIDGE', 'OBJECTID': 69185, 'L_ZIP': '15014', 'LHI': 847, 'RSTATE': 'PA', 'EDIT_USER': 't096517', 'FULL_NAME': '10TH AVE', 'FEATURE_KE': 69185, 'Shape_Leng': 495.36588114, 'R_STREET_I': 1, 'L_STREET_I': 1, 'ST_NAME': '10TH', 'LCOUNTY': 'ALLEGHENY', 'RLO': 804, 'LSTATE': 'PA', 'ST_TYPE': 'AVE', 'RHI': 804, 'RCOUNTY': 'ALLEGHENY', 'SPEED': 35, 'color': 0}}

In [43]:
import random

for i in range(len(dfsimplified['color'])):
    dfsimplified['color'][i] = f'{random.choice(range(0,10))}'

#display(dfsimplified)
#with open("Raw File/alleghenycounty_streetcenterlines202202.geojson") as f:
#    newjson = json.load(f)

#A Python dictionary containing properties to be added to each GeoJSON Feature
#Convert the dictionary to a list
properties_list=list(zip(dfsimplified['id'].tolist(), dfsimplified['color'].tolist()))
#print("1")
count = 0
#Loop over GeoJSON features and add the new properties
for feat in streets['features']:
    if(count%2000 == 0):
            print(properties_list[count][1])
    feat['properties']["color"] = properties_list[count][1]
    
    count+=1

#print("2")
#print(streets['features'][0])
#Write result to a new file
with open('update.geojson', 'w') as f:
    json.dump(streets, f)

<ipython-input-43-955baf5686f1>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfsimplified['color'][i] = f'{random.choice(range(0,10))}'

6
6
3
8
8
6
0
7
8
7
7
1
5
1
3
8
0
1
7
7
0
9
0
5
0
8
6
4
9
1
8
7
3
7
5
5
4
6
1
4
0